
name: Build and Push Python Image to GCP
on:
  push:
    branches: [ main ]
  jobs:
    build-push-gcp:
      name: Build and Push to GCP
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: flight-delays
        PROJECT_ID: infra-hulling-390616
        REGION: us-west2
      steps: 
      - name: Checkout
        uses: actions/checkout/@v2
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image 
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client # aunthenticate
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker env.REGION-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

