---
name: Build and Push Python Image to GCP
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcp:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flight-delays
      PROJECT_ID: infra-hulling-390616
      REGION: us-west2
    steps: 
    - name: Checkout
      uses: actions/checkout/@v2

    - id: 'auth' # aunthenticate
      name: 'Authenticate to Google'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1

    - name: Build Docker Image 
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client # aunthenticate to rep
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker env.REGION-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push env.REGION-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

